project_name: fakessh

builds:
  - &default
    skip: true
    binary: fakessh
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.goversion={{ .Env.GOVERSION }}"
      - -X "main.buildTime={{ .Env.BUILD_TIME }}"
      - -X "main.commitId={{ .Env.COMMIT }}"
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
  
  - <<: *default
    id: default
    skip: false
    flags:
      - -trimpath
  
  # - <<: *default 
  #   id: nogitserver
  #   skip: false
  #   flags:
  #     - -trimpath
  #     - -tags "ignore_gitserver"

archives:
  - id: default
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
  
  # - id: nogitserver
  #   builds:
  #     - nogitserver
  #   name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_nogitserver"
  #   format_overrides:
  #     - goos: windows
  #       format: zip