{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    mkEnableOption
    mkPackageOption
    mkOption
    mkIf
    mkMerge
    types
    optionals
    getExe
    escapeShellArg
    concatStringsSep
    optional
    ;

  cfg = config.services.fakessh;

  configFile =
    if cfg.configFile != null
    then cfg.configFile
    else
      pkgs.writeText "fakessh-config.toml" ''
        # Auto-generated by NixOS module
        ${cfg.extraConfig}
      '';
in
{
  options.services.fakessh = {
    enable = mkEnableOption "Fake SSH Server service";

    package = mkPackageOption pkgs "fakessh" { };

    port = mkOption {
      type = types.nullOr types.port;
      default = null;
      description = ''
        Port number to listen on.
        Must be set if configFile is not specified, and will override the port in the config file.
      '';
      example = 2222;
    };

    hostKey = mkOption {
      type = types.path;
      default = "/etc/fakessh/ssh_host_key";
      description = "Path to the host private key file.";
      example = "/etc/fakessh/ssh_host_key";
    };

    generateHostKey = mkOption {
      type = types.bool;
      default = true;
      description = "Whether to automatically generate the SSH host key if it doesn't exist.";
    };

    hostKeyType = mkOption {
      type = types.str;
      default = "ed25519";
      description = "Key type for auto-generated host key.";
      example = "rsa";
    };

    configFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to an external configuration file. Mutually exclusive with `extraConfig`.";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra configuration written to a generated config file (used when `configFile` is null).";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      users.groups.fakessh = { };
      users.users.fakessh = {
        group = "fakessh";
        isSystemUser = true;
      };

      systemd.tmpfiles.rules = [
        "d /etc/fakessh 0750 root fakessh -"
      ];

      systemd.services.fakessh = {
        description = "Fake SSH Server";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];

        serviceConfig = {
          ExecStart = concatStringsSep " " (
            [
              (getExe cfg.package)
              "-key ${escapeShellArg (toString cfg.hostKey)}"
              "-config ${escapeShellArg (toString configFile)}"
            ]
            ++ optional (cfg.port != null) "-port ${toString cfg.port}"
          );

          Restart = "always";
          RestartSec = 30;
          Type = "simple";

          # Hardening
          User = "fakessh";
          Group = "fakessh";
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          PrivateDevices = true;
          PrivateTmp = true;
          ReadOnlyPaths = [ "/" ];
          ReadWritePaths = [ "/etc/fakessh" ];
        };
      };
    }

    # Host-key auto-generation
    (mkIf cfg.generateHostKey {
      systemd.services.fakessh-keygen = {
        description = "Generate FakeSSH Host Key";
        wantedBy = [ "fakessh.service" ];
        before = [ "fakessh.service" ];
        path = [ pkgs.openssh ];

        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };

        script = ''
          if [ ! -f ${escapeShellArg (toString cfg.hostKey)} ]; then
            echo "Generating new SSH host key..."
            ${getExe cfg.package} \
              -gen \
              -key ${escapeShellArg (toString cfg.hostKey)} \
              -type ${escapeShellArg cfg.hostKeyType}
            chown root:fakessh ${escapeShellArg (toString cfg.hostKey)}
            chmod 640 ${escapeShellArg (toString cfg.hostKey)}
          fi
        '';
      };

      systemd.services.fakessh = {
        requires = [ "fakessh-keygen.service" ];
      };
    })
  ]);
}
