name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - 
        name: Set Build Info
        id: "info"
        run: |
          echo "::set-output name=commit::$(git rev-parse --short HEAD)"
          echo "::set-output name=buildtime::$(TZ='Asia/Shanghai' date '+%Y/%m/%d-%H:%M:%S %Z')"
          echo "::set-output name=goversion::$(go version)"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT: ${{ steps.info.outputs.commit }}
          BUILD_TIME: ${{ steps.info.outputs.buildtime }}
          GOVERSION: ${{ steps.info.outputs.goversion }}
